# Generated by Django 6.0.4 on 2026-04-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "ticker",
                    models.CharField(
                        db_index=True,
                        help_text="The symbol for a listing.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="False indicates this listing is can no longer be traded.",
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=128, null=True),
                ),
                (
                    "sector",
                    models.CharField(blank=True, default="", max_length=128, null=True),
                ),
                (
                    "industry",
                    models.CharField(blank=True, default="", max_length=128, null=True),
                ),
            ],
            options={
                "unique_together": {("name", "ticker")},
            },
        ),
    ]
