# Generated by Django 6.0.4 on 2026-04-15 01:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingUpload",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "listing_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "imported",
                    models.BooleanField(
                        default=False,
                        help_text="Marked True when the task has processed this file to import listings data.",
                    ),
                ),
                (
                    "latest_task_id",
                    models.CharField(
                        blank=True,
                        help_text="This field can hold the task_id when using an async task to process the listings_file.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_on",
            },
        ),
    ]
