# Generated by Django 6.0.4 on 2026-04-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ListingUpload",
        ),
    ]
